### ISSUE TITLE
Channel name link

### ISSUE THREAD

**Issue by cjeffcoat2** [rogerclarkmelbourne/OpenGD77CPS#31]
Can someone please verify, it appears that you are able to create a longer channel name in the tree view on the left by clicking on an existing channel and editing it. If you double click on the channel and edit the name field in the channel details screen, the length allowed appears to be shorter￼

**Comment by rogerclarkmelbourne** [comment]
Looks like a bug on the Channel Details screen. The field size of the name is 16 characters, and I've tested that the OpenGD77 can display 16 characters for the channel name

Its possible that the official firmware could only handle 15 characters + a terminator byte (of 0xff), but since this CPS now only works with the OpenGD77 there is no need to retain a 15 char limit on the Channel screen

**Comment by rogerclarkmelbourne** [comment]
I've just done a local  fix for this and it will be in the next release, in the mean time, if you need 16 char names, you'll need to rename the chars in the tree view and probably not open that channel in the Channel screen, as it may remove the 16th character
