### ISSUE TITLE
Possible Virus ?

### ISSUE THREAD

**Issue by g7jiq** [rogerclarkmelbourne/OpenGD77CPS#48]
I have just tried to install the latest (13th Dec) update of OpenDG77CPS, 
My virus checker (AVG or Avast 2 PCs) Both show it is infected with FileRepMetagen[Adw] and promptly deletes it.
Any Ideas ?
Is this a false possitive ?

**Comment by rogerclarkmelbourne** [comment]
This is not the first time that virus checkers say the CPS has a virus

I just checked with Windows 10 Bit Defender on another machine and it didn't find any problems.

If you are concerned that it may contain a virus, which is always a possibility with any file even if your virus scanner says it doesn't have a virus...
Then don't install this version, as the change since the last version is a minor bug fix to the representation of one field of data on the Calibration screem

There are no new features etc.

**Comment by g7jiq** [comment]
Thanks for you reply, 
Just wanted to check all was ok,
Sounds like its possably a false possitive,
I will run it on my test pc with just the windows defender running, and check the system after to see if alls good,
This is what I normaly do with suspect files.

**Comment by g7jiq** [comment]
I can confirm all is clear after it is installed, 
It looks to me like its the install package thats throwing up the false possitive.
I didn't want to alarm anyone, 
But just wanted to be sure incase anyone else had it flag up.

**Comment by rogerclarkmelbourne** [comment]
The problem is usually the installer.

The anti-virus companies flag any installer package made with the opensource / free installer makers as a virus regardless of whether it is or not. Mainly because the virus writers use the same installer makers.

I've tried using both of the 2 leading free installer makers, InnoSetup and Nullsoft Installer (NSIS), and the both have the same problem. The commercial installer makers costs $$$$$, so that's out of the question for something I'm providing for free.

Additionally I don't have a signing certificate as that costs $$, and I doubt it would make any difference, because in my commercial work, I also use InnoSetup, and one of my clients digitally signs the installer, with their own corporate security certificate, but sometimes anti-virus systems still flag the installer as a virus.
