### ISSUE TITLE
Boot Screen - Can't add space before /after text in line1 / line2

### ISSUE THREAD

**Issue by Wireheadbe** [rogerclarkmelbourne/OpenGD77CPS#59]
Spaces seem to be automatically removed now, causing line1/line2 to be concatenated in Talker Alias.
In the past, we could add e.g. a space in line2, causing the fields to be split.

**Comment by rogerclarkmelbourne** [comment]
I don't recall adding code to do this. Can you reference the line in the code which does it ?

Its possibly in the firmware

**Comment by Wireheadbe** [comment]
It's really in the CPS, where you edit the codeplug. In the past, I just added a space after line1. Now when I do that, it's removed after setting the focus to another field.

**Comment by rogerclarkmelbourne** [comment]
It looks like the Trim was added a few commits ago, but as it seemed to part of a bulk update with a load of other changes, I'm not  entirely sure why that was changed.

I'd need to ask the other developer F1RMB if he has any knowledge of why that may have been added.

Also, I'd have to test what effects are caused by removing it. e.g. perhaps screws up the boot screen.

**Comment by f1rmb** [comment]
Hi,

   The boot lines trimming were added in a huge cleaning pass (by mistake). I raised a PR #60 


Cheers.
...
Daniel

**Comment by rogerclarkmelbourne** [comment]
OK. I didn't remember adding them. ;-)

**Comment by rogerclarkmelbourne** [comment]
See https://github.com/rogerclarkmelbourne/OpenGD77CPS/releases/tag/R2021.03.02.01
