### ISSUE TITLE
Please add a licence

### ISSUE THREAD

**Issue by redfast00** [rogerclarkmelbourne/OpenGD77CPS#9]
I suggest something like MIT or GNU GPLv3. Otherwise, if not explicitly stated, people can't legally use, modify or share the software (see https://opensource.stackexchange.com/q/1720).

**Comment by rogerclarkmelbourne** [comment]
I didn't write this code, hence I can't assign a license to it.

This repo contains a modified version of the official Radioddity CPS, which I made by decrypting, de-obfuscating, and then de-compiling from their DotNet EXE.
And then then fixing the de-compilation artifacts and re-compiling and then made changes and additions.

**Comment by redfast00** [comment]
@rogerclarkmelbourne oh, okay. I'm currently writing a replacement OpenGD77CPS in Java (with javafx as GUI library) inspired by your blog post https://www.rogerclark.net/designing-a-cps-data-structure/. The advantage of this over the current CPS is that it will work cross-platform (on Windows, Mac and Linux), the code should be much more readable (no more decompiled code), it will be easier to modify if the firmware changes and it will be open source. In order to do this, I will need to understand the protocol and memory-layout that is currently used by OpenGD77. My current plan is to do this by reading the opengd77cps code, but this might be pretty time-consuming. Is there a better source of documentation available somewhere?

**Comment by rogerclarkmelbourne** [comment]
There is no documentation for the codeplug format. You could look in the OpenGD77 or the CPS source at the data structures

The OpenGD77 structures are probably easier to read but they are incomplete as we don't handle all the codeplug e.g Emergency systems and Scanlists etc etc are not supported.

BTW.

There is a cross platform CPS for the MD-380 written in QT, and someone else also started to write another cross platform CPS for the GD-77, but they didnt get too far.
There is also a cross platform codeplug loader for muliple radios, but it doesnt support the OpenGD77 comms protocol.

Sorry, I can't remember the URLs for any of these, but I'm sure you can find them,

BTW.

I'm surprised you are using Java, because of its quasi proprietary nature.
Modifing the MD-380 QT version may be a more open way to do it.

I'm not even sure its worth the bother of writing a CPS.  A lot of people are happy to work with CSV files for the various data blocks, and then using a tool like the one written by Colin G4EML to convert the CSV's into the binary codeplug format.
BTW. Colin's utility is closed source but free to download
